### PR TITLE
Update ReadMe doc

### PR DESCRIPTION
**Pull request by cruzfernando**
New copy and links

Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [ ] Appropriate changes to the README.md included in PR.

### CODE REVIEW

**Comment by grant** [comment]
@cruzfernando Please sign the CLA via the link above.

**Comment by cruzfernando** [comment]
I registered by account and also joined the GoogleCloudPlatform group. Do I need to execute anything else on my end or would could you reapprove the changes submitted?

**Comment by grant** [comment]
Hi @cruzfernando, thanks for your patience.

> Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

So please reply with that.

**Comment by grant** [comment]
(or I can comment and trigger the bot 😄)

**Pull request merged**
